server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
  opentelemetry:
    logging:
      export:
        otlp:
          endpoint: ${GRAFANA_URL:http://localhost:4318}/v1/logs
    tracing:
      export:
        otlp:
          endpoint: ${GRAFANA_URL:http://localhost:4318}/v1/traces
  otlp:
    metrics:
      export:
        url: ${GRAFANA_URL:http://localhost:4318}/v1/metrics

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
    io.opentelemetry.exporter: DEBUG
    io.opentelemetry.sdk.logs: DEBUG
