apache_commons_collection_version=4.5.0
apache_commons_lang_version=3.20.0
apache_tika_version=3.3.0
aws_version=2.46.21
guava_version=33.6.0-jre
mapstruct_version=1.6.3
spring_cloud_version=2025.1.1
junit_version=6.0.0
junit_platform_suite_version=6.1.1
assertj_version=4.0.0-M1
test_containers_version=1.21.4
test_containers_core_version=2.0.5

cucumber_version=7.34.4