
CREATE TABLE public.mp3_files (
	id         int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	bucket     text NOT NULL,
	object_key uuid NOT NULL,
	CONSTRAINT uq_mp3_files_bucket_object_key UNIQUE (bucket, object_key)
);