server:
  port: ${RESOURCE_SERVICE_PORT:8080}
spring:
  application:
    name: resource-service
  config:
    import:
      - optional:file:.env[.properties]
#      - optional:file:../.env[.properties]
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://${RESOURCE_POSTGRES_HOST}:${RESOURCE_POSTGRES_PORT}/${RESOURCE_POSTGRES_DB}?sslmode=disable
    username: ${RESOURCE_POSTGRES_USER}
    password: ${RESOURCE_POSTGRES_PASSWORD}

  http:
    client:
      service:
        group:
          song:
            base-url: http://song-service
  jackson:
    stream-write-features:
      write-numbers-as-strings: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}


app:
  csv-string:
    delimiter: ${CSV_STRING_DELIMITER:,}
    max-length: ${CSV_STRING_MAX_LENGTH:200}

aws:
  s3:
    access-key: ${RESOURCE_SERVICE_AWS_S3_ACCESS_KEY}
    secret-key: ${RESOURCE_SERVICE_AWS_S3_SECRET_KEY}
    endpoint: ${RESOURCE_SERVICE_AWS_S3_ENDPOINT:http://localhost:4566}
    region: ${RESOURCE_SERVICE_AWS_S3_REGION:us-east-1}
    bucket-name: ${RESOURCE_SERVICE_AWS_S3_BUCKET_NAME}

application:
  kafka:
    topic:
      song:
        name: ${KAFKA_TOPIC_SONG_NAME:songs}

logging:
  level:
    org.springframework.boot.context.config: DEBUG
    org.springframework.retry: DEBUG
    org.springframework.core.retry: DEBUG
    org.springframework.resilience: TRACE
    org.springframework.kafka: DEBUG
