server:
  port: ${RESOURCE_SERVICE_PORT:8080}
spring:
  application:
    name: resource-service
  config:
    import:
      - optional:file:.env[.properties]
#      - optional:file:../.env[.properties]
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://${RESOURCE_POSTGRES_HOST}:${RESOURCE_POSTGRES_PORT}/${RESOURCE_POSTGRES_DB}?sslmode=disable
    username: ${RESOURCE_POSTGRES_USER}
    password: ${RESOURCE_POSTGRES_PASSWORD}

  http:
    client:
      service:
        group:
          song:
            base-url: http://song-service
          storage:
            base-url: http://storage-service
  cloud:
    circuitbreaker:
      http-services:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST:localhost}:7080/realms/microservices/protocol/openid-connect/certs
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:7080}/realms/microservices

  jackson:
    stream-write-features:
      write-numbers-as-strings: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.epam.*"
        spring.json.value.default.type: com.epam.resource.dto.kafka.ResourceProcessedEvent
        spring.json.use.type.headers: false
    template:
      observation-enabled: true
    listener:
      observation-enabled: true
resilience4j:
  circuitbreaker:
    instances:
      storageService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
#        ignoreExceptions:
#          - com.epam.*

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}


app:
  csv-string:
    delimiter: ${CSV_STRING_DELIMITER:,}
    max-length: ${CSV_STRING_MAX_LENGTH:200}

aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    endpoint: ${AWS_S3_ENDPOINT:http://localhost:4566}
    region: ${AWS_S3_REGION:us-east-1}
    bucket-name: ${AWS_S3_BUCKET_NAME}

application:
  kafka:
    topic:
      song:
        name: ${KAFKA_TOPIC_SONG_NAME:songs}
      song-created:
        name: ${KAFKA_TOPIC_SONG_CREATED_NAME:song-created}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
  opentelemetry:
    logging:
      export:
        otlp:
          endpoint: ${GRAFANA_URL:http://localhost:4318}/v1/logs
    tracing:
      export:
        otlp:
          endpoint: ${GRAFANA_URL:http://localhost:4318}/v1/traces
  otlp:
    metrics:
      export:
        url: ${GRAFANA_URL:http://localhost:4318}/v1/metrics
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c

logging:
  level:
    com.epam: INFO
    org.springframework.boot.actuator.autoconfigure.opentelemetry: DEBUG
    org.springframework.boot.docker.compose: DEBUG
