spring:
  config:
    import:
      - optional:file:.env[.properties]
#      - optional:file:../.env[.properties]
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://${RESOURCE_POSTGRES_HOST}:${RESOURCE_POSTGRES_PORT}/${RESOURCE_POSTGRES_DB}?sslmode=disable
    username: ${RESOURCE_POSTGRES_USER}
    password: ${RESOURCE_POSTGRES_PASSWORD}

  http:
    client:
      service:
        group:
          song:
            base-url: http://${SONG_SERVICE_HOST}:${SONG_SERVICE_PORT}
  jackson:
    stream-write-features:
      write-numbers-as-strings: true
app:
  csv-string:
    delimiter: ${CSV_STRING_DELIMITER:,}
    max-length: ${CSV_STRING_MAX_LENGTH:200}


logging:
  level:
    org.springframework.boot.context.config: DEBUG